using TeleFlow.Telegram.SchemaGenerator.Models;

namespace TeleFlow.Telegram.SchemaGenerator.Generation;

internal static class GeneratedFileHeader
{
    public static void Append(List<string> lines, TelegramSchemaMetadata metadata, string kind)
    {
        lines.Add("// <auto-generated>");
        lines.Add("//   This file was generated by TeleFlow.Telegram.SchemaGenerator.");
        lines.Add($"//   Kind: {kind}");
        lines.Add($"//   Source: {metadata.SourceUrl}");
        lines.Add($"//   Source snapshot: {metadata.SourceCapturedAtUtc:O}");
        lines.Add($"//   Source SHA-256: {metadata.SourceSha256}");
        lines.Add($"//   Telegram Bot API version: {metadata.TelegramBotApiVersion}");
        lines.Add($"//   Telegram Bot API release: {metadata.TelegramBotApiReleasedAt}");
        lines.Add($"//   Telegram Bot API changelog: https://core.telegram.org/bots/api-changelog#{metadata.TelegramBotApiChangelogAnchor}");
        lines.Add($"//   Schema version: {metadata.SchemaVersion}");
        lines.Add($"//   Generator version: {metadata.GeneratorVersion}");
        lines.Add("//   Do not edit this file manually.");
        lines.Add("// </auto-generated>");
    }
}
